# IN ORDER TO USE THIS CONFIG FILE, RENAME IT AND REMOVE THE ".example" PART OF THE FILENAME!
#
# CrewLink peer to peer connection configuration.
#
# This file lets you modify how CrewLink connects players to each other.
#
# CrewLink uses peer to peer connections to send voice and game state data between players. This means that every player
# has to be able to connect to every other player some way or another in order for CrewLink to work. Below you can tweak
# the mechanisms CrewLink uses to establish peer to peer connections.

# Force CrewLink to only work through TURN servers. This is great if you want to protect the IP addresses of players
# as no direct connection will be made. At least one TURN server is required if set to true.
forceRelayOnly: false

# If you run into connection issues, you may want to add your own TURN server here.
iceServers:
  # Google's STUN server is used by default
  - urls: 'stun:stun.l.google.com:19302'
#   - urls: 'turn:example.com'
#     username: 'TurnUsername'
#     credential: 'TurnPassword'
#   - urls: 'stun:example.com'
#     username: 'StunUsername'
#     credential: 'StunPassword'